services:
  appointments:
    build: ./appointments
    ports:
      - "3001:3001"
    command: npm run start:prod
  customers:
    build: ./customers
    ports:
      - "3002:3002"
    command: npm run start:prod
  sales:
    build: ./sales
    ports:
      - "3003:3003"
    command: npm run start
