services:
  datadog:
    image: datadog/agent:7.57.2
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_ENV=${USER}-local
      - DD_DOGSTATSD_SOCKET=/var/run/dogstatsd/dogstatsd.sock
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_LOGS_ENABLED=true
      - DD_OTLP_CONFIG_LOGS_ENABLED=true
    volumes:
      - /var/run/dogstatsd:/var/run/dogstatsd
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126"
      - "8125:8125/udp"
      - "4317:4317"

  appointments:
    build: ./appointments
    ports:
      - "3001:3001"
    command: npm run start
    environment:
      - DD_AGENT_HOST=datadog
      - DD_TRACE_AGENT_PORT=8126
      - DD_SERVICE=appointments
  customers:
    build: ./customers
    ports:
      - "3002:3002"
    command: npm run start
    environment:
      - DD_AGENT_HOST=datadog
      - DD_TRACE_AGENT_PORT=8126
      - DD_SERVICE=customers
  sales:
    build: ./sales
    ports:
      - "3003:3003"
    command: npm run start
    environment:
      - DD_AGENT_HOST=datadog
      - DD_TRACE_AGENT_PORT=8126
      - DD_SERVICE=sales
