services:
  sales:
    build: ./sales
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    command: bun start
  appointments:
    build: ./appointments
    ports:
      - "4000:4000"
    command: npm run start:prod
