serve:
  port: 3000
sources:
  - name: Appointments
    handler:
      openapi:
        endpoint: http://localhost:3001/
        source: http://localhost:3001/api-json
    transforms:
      - prefix:
          mode: bare
  - name: Customers
    handler:
      grpc:
        endpoint: localhost:3002
        source: ../customers/src/customers/customers.proto
  - name: Sales
    handler:
      graphql:
        endpoint: http://localhost:3003/graphql
